name: Sync Node

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * ?'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download clash config
      run: wget  https://free.xclash.workers.dev -O config.yml
    - name: Push config
      run: |
        cd scripts
        git config --global user.email "ci@github.com"
        git config --global user.name "CI" 
        git add config.yml 
        git commit -m "update config"
        git push
