name: Sync Node

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * ?'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download clash config
      run: |
        wget  https://free.xclash.workers.dev -O clash.yml
        wget https://raw.fastgit.org/Pawdroid/Free-servers/main/sub -O v2ray
    - name: Push config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Action"
        echo $(date +%Y-%m-%d" "%H:%M:%S) > update
        git add .
        git commit -m "update config"
        git push -f
